# Generated by Django 4.1 on 2023-04-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squarelet_auth_organizations", "0007_delete_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitlement",
            name="resources",
            field=models.JSONField(default=dict),
        ),
    ]
